#!/bin/bash

# =============================================================================
# GPU Auto-Detect & Udev Rule Generator
# =============================================================================
# Description: 
#   Scans PCI bus for VGA/3D controllers. Identifies iGPU vs dGPU.
#   Generates a targeted udev rule based on the dGPU's precise Bus ID.
#   Prevents configuration errors if the GPU moves slots or is removed.
# =============================================================================

RULE_FILE="/etc/udev/rules.d/99-gpu-config.rules"
LOG_FILE="/var/log/gpu-autodetect.log"

# Ensure script is run as root
if [[ $EUID -ne 0 ]]; then
   echo "Error: This script must be run as root." 
   exit 1
fi

echo "Starting GPU Auto-Detect..." > "$LOG_FILE"

# 1. DETECT GPUS using lspci
# -----------------------------------------------------------------------------
# -nn: Show numeric vendor:device IDs
# -D:  Show full domain:bus:slot.func (0000:01:00.0)
# grep -E "VGA|3D": Matches 'VGA compatible controller' or '3D controller'
# -----------------------------------------------------------------------------
ALL_GPUS=$(lspci -nnD | grep -E "VGA|3D")

if [[ -z "$ALL_GPUS" ]]; then
    echo "Critical: No Graphics Controllers found." | tee -a "$LOG_FILE"
    exit 1
fi

# 2. IDENTIFY iGPU vs dGPU
# -----------------------------------------------------------------------------
# Heuristic: iGPU is typically on Bus 00 (0000:00:xx.x). 
# dGPU is typically on a secondary Bus (e.g., 0000:01:xx.x or higher).
# We also check generic Vendor IDs: Intel (8086) is usually iGPU.
# -----------------------------------------------------------------------------

IGPU_BUS=""
DGPU_BUS=""
DGPU_VENDOR=""
DGPU_DEVICE=""

# Loop through each detected GPU line
while IFS= read -r line; do
    BUS_ID=$(echo "$line" | awk '{print $1}')
    VENDOR_ID=$(echo "$line" | grep -oP '\[\K[0-9a-f]{4}:[0-9a-f]{4}(?=\])')
    
    # Check if it's an Intel iGPU (Common Vendor ID: 8086)
    if [[ "$VENDOR_ID" =~ ^8086 ]]; then
        IGPU_BUS="$BUS_ID"
        echo "Found iGPU: $line" | tee -a "$LOG_FILE"
    else
        # Assume non-Intel (NVIDIA/AMD) on non-zero bus is dGPU
        # This can be refined for AMD APUs by checking bus address (usually > 00:02.0)
        DGPU_BUS="$BUS_ID"
        DGPU_VENDOR=$(echo "$VENDOR_ID" | cut -d: -f1)
        DGPU_DEVICE=$(echo "$VENDOR_ID" | cut -d: -f2)
        echo "Found dGPU: $line" | tee -a "$LOG_FILE"
    fi
done <<< "$ALL_GPUS"

# 3. VERIFY LOCATION & RELATIONSHIP
# -----------------------------------------------------------------------------
if [[ -z "$DGPU_BUS" ]]; then
    echo "Notice: No Discrete GPU found. Cleaning up rules." | tee -a "$LOG_FILE"
    if [[ -f "$RULE_FILE" ]]; then
        rm "$RULE_FILE"
        echo "Removed obsolete rule file." | tee -a "$LOG_FILE"
        udevadm control --reload-rules && udevadm trigger
    fi
    exit 0
fi

echo "Configuration Check: dGPU located at $DGPU_BUS" | tee -a "$LOG_FILE"

# 4. GENERATE UDEV RULE
# -----------------------------------------------------------------------------
# We use the PCI Bus ID (KERNELS) to strictly bind the rule to this specific card.
# This avoids applying the rule to the iGPU by mistake.
#
# CUSTOMIZE: Edit the 'RUN' or 'ATTR' fields below for your specific contest goal.
# Examples:
#   - Power Management: ATTR{power/control}="on"
#   - VFIO Binding: RUN+="/usr/bin/vfio-pci-override.sh"
#   - Permissions: OWNER="root", GROUP="video", MODE="0666"
# -----------------------------------------------------------------------------

cat <<EOF > "$RULE_FILE"
# Auto-Generated by gpu_autodetect.sh on $(date)
# dGPU: $DGPU_BUS (Vendor: $DGPU_VENDOR Device: $DGPU_DEVICE)

# Match strictly by PCI Slot Name (Bus Address) to ensure we target the dGPU
ACTION=="add", KERNELS=="$DGPU_BUS", SUBSYSTEM=="pci", TAG+="uaccess", TAG+="seat", ENV{ID_GPU_TYPE}="discrete"

# Optional: Nvidia Specific Tuning (Uncomment if needed)
# ACTION=="add", KERNELS=="$DGPU_BUS", DRIVER=="nvidia", ATTR{power/control}="auto"

EOF

echo "Success: Udev rule generated at $RULE_FILE" | tee -a "$LOG_FILE"

# 5. APPLY CHANGES
# -----------------------------------------------------------------------------
udevadm control --reload-rules
udevadm trigger --action=add --sysname-match="$DGPU_BUS"

echo "Udev rules reloaded and triggered for $DGPU_BUS." | tee -a "$LOG_FILE"

